server:
  port: 8081
spring:
  application:
    name: cart-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dzm123%*
    url: jdbc:mysql://119.18.193.77:3306/cart_db

    #Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 3
    maxActive: 20
    minIdle: 3
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat,wall,slf4j
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: true
      exclude: static/*
  redis:
        host: 47.95.109.142
        port: 6379
  kafka:
    bootstrap-servers: 47.95.109.142:9092
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-servers}

#feign配置
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: false
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: false
  client:
    default-config: default

#端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

#日志配置
logging:
  level:
    root: info
    com.humor.cart.service.api.ProductService: debug
  path: /logs
  file:
    max-size: 1MB
